name: macOS Py3.11

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"

jobs:
  build:
    uses: ./.github/workflows/python-package-template.yml
    with:
      os: macos-latest
      python: "3.11"
